### ISSUE TITLE
Manage file

### ISSUE THREAD

**Issue by henryust12** [eburen/FEEDOURMIND_EDIT#2]
Please make folder to contain one type of file.
For **_example_**, image file in one img folder.
`/assets/images` or /`assets/images/logo/`
`/assete/css/`
`/assets/js/`
When you created that folders, next please set file path in every file.

For **_example_**, in index.php
`<link rel="stylesheet" href="assets/css/reset.css">`

_Assets = Folder_

<br><br><br>
_**日本語**_
1種類のファイルが含まれるフォルダを作成してください。
たとえば、1つのimgフォルダにある画像ファイル。
/ assets / imagesまたは/ assets / images / logo /
/ assets / css /
/ assets / js /
そのフォルダを作成したら、次にすべてのファイルにファイルの場所を設定してください。

たとえば、index.phpで
<link rel = "stylesheet" href = "assets / css / reset.css">

<img width="1904" alt="Screenshot 0003-10-13 at 17 45 26" src="https://user-images.githubusercontent.com/59615137/137099989-5f62f094-c22e-4d99-87c2-4bb906690e6d.png">

**Comment by eburen** [comment]
nice job dude
