### ISSUE TITLE
Duplicated file issue

### ISSUE THREAD

**Issue by henryust12** [eburen/FEEDOURMIND_EDIT#9]
## Duplicated css file.
`File name : style.css`
`Direectory : FEEDOURMIND_EDIT/style.css` and `FEEDOURMIND_EDIT/assets/css/style.css`   
![1](https://user-images.githubusercontent.com/28552725/141979698-3e88d5f7-7950-4ddb-bdf8-598d79d56916.png)
![2](https://user-images.githubusercontent.com/28552725/141979703-efdc30c3-293b-4ec4-8895-1d026459896d.png)

**Comment by eburen** [comment]
The issue was fixed after San Lin oo had pushed the folder.
